---
extends: "@elastic/eslint-config-kibana"

rules:
  quotes: warn
  no-use-before-define: warn
  no-empty: warn
  space-before-function-paren: warn
  no-restricted-globals: warn
  prefer-const: warn