---
extends: "@elastic/eslint-config-kibana"

rules:
  no-var: warn
  no-unused-vars: warn
  semi: warn
  one-var: warn
  new-cap: warn
  space-unary-ops: warn
  dot-notation: warn
  quotes: warn
  no-use-before-define: warn
  no-empty: warn
  space-before-function-paren: warn
  no-restricted-globals: warn
  prefer-const: warn